baseURL = "https://myquay.github.io/hugo-theme-peripheral-example"
languageCode = "en-us"
title = "Peripheral example"
themesDir = "themes"
theme = "hugo-theme-peripheral"
enableGitInfo = true
DefaultContentLanguage = "en"


[Params.Peripheral.GitInfo]
    enabled = true
    repository = "https://github.com/myquay/hugo-theme-peripheral-example"
    abbreviatedHash = "{{AbbreviatedHash}}"
    hash = "{{Hash}}"
    subject = "{{Subject}}"
    branch = "main"

[mediaTypes]
    [mediaTypes."application/atom+xml"]
    suffixes = ["xml"]

[outputFormats.RSS]
    mediaType = "application/rss+xml"
    baseName = "rss"

[outputFormats.Atom]
    mediaType = "application/atom+xml"
    baseName = "atom"

[outputs] 
    section = ["HTML", "RSS", "Atom"]